# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs: 
- deployment:
  displayName: LinuxDeployTest # Job の表示名です。任意の名前にご変更ください。
  environment: 
    name: 'test0609' # Environment 名です。ご設定された Environment 名へご変更ください。
    resourceName: 'vhmitsuUbuntu' # Environment に登録した Resource 名です。ご登録された Resource 名へご変更ください。
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)'
            Contents: '**'
            TargetFolder: '/home/azureuser/target' 